#Is the 4-sunlet ideal included in the ideal of model 13 of type (2,1,1)?

#build the 4 sunlet
N = graph_from_edges(Directed, [[1,5],[2,1],[2,6],[3,2],[3,7],[3,4],[4,1],[4,8]])
net = phylogenetic_network(N)
PM = cavender_farris_neyman_model(net)
R, q = model_ring(PM)
S, a = parameter_ring(PM)
phi = parametrization(PM)
H = components_of_kernel(2, phi, show_progress = true)
I = ideal(reduce(vcat, collect(values(H))))

#Ideal generated by
#  -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] + q[2,1,1,2]*q[1,2,2,1]

#build anc check model 13 of type (2,1,1)
# N = graph_from_edges(Directed, [[1,5],[2,1],[2,6],[3,2],[3,7],[3,4],[4,1],[4,8]])
# net = phylogenetic_network(N)
# PM = cavender_farris_neyman_model(net)
#NOTE: Network Model obtaine from test.jl file
R13, q13 = model_ring(PM13)
S13, a13 = parameter_ring(PM13)
phi13 = parametrization(PM13)
H13 = components_of_kernel(2, phi13, show_progress = true)
I13 = ideal(reduce(vcat, collect(values(H13))))