# trying to generalise Lemma 2.14 from IDENTIFIABILITY OF PHYLOGENETIC LEVEL-2 NETWORKS UNDER THE JUKES-CANTOR MODEL

N = draw_network([3,5],[3,1,0])
phi = parametrization(N)
H = components_of_kernel(2, phi, show_progress = true)
I = ideal(reduce(vcat, collect(values(H))))

#ideal: -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] + q[2,1,1,2]*q[1,2,2,1]

G2 = graph_from_edges(Directed, [[1,5],[1,2],[2,3],[4,3],[5,4],[2,8],[3,7],[4,9],[1,6],[6,5],[6,10]])
net2 = phylogenetic_network(G2)
N2 = cavender_farris_neyman_model(net2)
phi2 = parametrization(N2)
H2 = components_of_kernel(2, phi2, show_progress = true)
I2 = ideal(reduce(vcat, collect(values(H2))))

#ideal: -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] + q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

G3 = graph_from_edges(Directed, [[1,5],[1,2],[2,3],[4,3],[5,4],[2,7],[3,9],[4,8],[1,6],[6,5],[6,10]])
net3 = phylogenetic_network(G3)
N3 = cavender_farris_neyman_model(net3)
phi3 = parametrization(N3)
H3 = components_of_kernel(2, phi3, show_progress = true)
I3 = ideal(reduce(vcat, collect(values(H3))))

#ideal: q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

G4 = graph_from_edges(Directed, [[1,5],[1,2],[2,3],[4,3],[5,4],[2,7],[3,10],[4,9],[1,6],[6,5],[6,8]])
net4 = phylogenetic_network(G4)
N4 = cavender_farris_neyman_model(net4)
phi4 = parametrization(N4)
H4 = components_of_kernel(2, phi4, show_progress = true)
I4 = ideal(reduce(vcat, collect(values(H4))))

#ideal: -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] + q[2,1,1,2]*q[1,2,2,1]

# the first and fourth calculation show that Lemma 2.14 a) is false!, we have found two distinct networks with different leaf labels
# on the top middle leaf which give the same ideal, hence not identifiable.

######################
# testing for part b #
######################

G = graph_from_edges(Directed, [[1,2],[3,2],[4,3],[2,7],[3,8],[1,4],[1,5],[5,6],[4,6],[5,9],[6,10]])
net = phylogenetic_network(G)
N = cavender_farris_neyman_model(net)
phi = parametrization(N)
H = components_of_kernel(2, phi, show_progress = true)
I = ideal(reduce(vcat, collect(values(H))))

#ideal: -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] + q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

G2 = graph_from_edges(Directed, [[1,2],[3,2],[4,3],[2,8],[3,7],[1,4],[1,5],[5,6],[4,6],[5,9],[6,10]])
net2 = phylogenetic_network(G2)
N2 = cavender_farris_neyman_model(net2)
phi2 = parametrization(N2)
H2 = components_of_kernel(2, phi2, show_progress = true)
I2 = ideal(reduce(vcat, collect(values(H2))))

#ideal: -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] + q[2,1,1,2]*q[1,2,2,1]

G3 = graph_from_edges(Directed, [[1,2],[3,2],[4,3],[2,9],[3,8],[1,4],[1,5],[5,6],[4,6],[5,7],[6,10]])
net3 = phylogenetic_network(G3)
N3 = cavender_farris_neyman_model(net3)
phi3 = parametrization(N3)
H3 = components_of_kernel(2, phi3, show_progress = true)
I3 = ideal(reduce(vcat, collect(values(H3))))

#ideal:  q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

G4 = graph_from_edges(Directed, [[1,2],[3,2],[4,3],[2,10],[3,8],[1,4],[1,5],[5,6],[4,6],[5,9],[6,7]])
net4 = phylogenetic_network(G4)
N4 = cavender_farris_neyman_model(net4)
phi4 = parametrization(N4)
H4 = components_of_kernel(2, phi4, show_progress = true)
I4 = ideal(reduce(vcat, collect(values(H4))))

#ideal:  -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] + q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

G5 = graph_from_edges(Directed, [[1,2],[3,2],[4,3],[2,7],[3,8],[1,4],[1,5],[5,6],[4,6],[5,10],[6,9]])
net5 = phylogenetic_network(G5)
N5 = cavender_farris_neyman_model(net5)
phi5 = parametrization(N5)
H5 = components_of_kernel(2, phi5, show_progress = true)
I5 = ideal(reduce(vcat, collect(values(H5))))

#ideal:  -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] - q[2,1,2,1]*q[1,2,1,2] + q[2,1,1,2]*q[1,2,2,1]

#examples 2 and 5 show that part b of the Lemma is false!

######################
# testing for part c #
######################

#this is false since lots of these networks already fill space, so relabelling the leafs will not change that fact and hence the networks stay non-distinguishable.

######################
# testing for part d #
######################

G = graph_from_edges(Directed, [[1,2],[2,3],[4,3],[5,4],[1,5],[1,6],[5,7],[7,6],[2,8],[3,9],[4,10],[6,11],[7,12]])
net = phylogenetic_network(G)
N = cavender_farris_neyman_model(net)
phi = parametrization(N)
H = components_of_kernel(2, phi, show_progress = true)
I = ideal(reduce(vcat, collect(values(H))))

# Ideal generated by
#   -q[2,2,2,2,1]*q[1,1,1,2,2] + q[2,2,1,2,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,2,2]
#   q[2,2,2,2,1]*q[2,1,1,1,2] - q[2,2,2,1,2]*q[2,1,1,2,1] - q[2,2,1,2,2]*q[2,1,2,1,1] + q[2,2,1,1,1]*q[2,1,2,2,2]
#   q[1,2,2,2,2]*q[1,1,1,1,1] - q[1,2,2,1,1]*q[1,1,1,2,2] - q[1,2,1,2,1]*q[1,1,2,1,2] + q[1,2,1,1,2]*q[1,1,2,2,1]
#   -q[2,2,2,2,1]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]
#   q[2,2,1,2,2]*q[1,1,1,1,1] - q[2,2,1,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,1,2,1]
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] + q[2,1,2,2,2]*q[1,2,1,1,2] - q[2,1,1,1,2]*q[1,2,2,2,2]
#   -q[2,2,2,1,2]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,1,2] - q[2,1,2,1,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,1,1]
#   q[2,2,2,2,1]*q[1,1,2,1,2] - q[2,2,2,1,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,2,1,1] + q[2,1,2,1,1]*q[1,2,2,2,2]
#   -q[2,2,2,2,1]*q[1,2,1,1,2] + q[2,2,2,1,2]*q[1,2,1,2,1] + q[2,2,1,2,2]*q[1,2,2,1,1] - q[2,2,1,1,1]*q[1,2,2,2,2]
#   q[2,1,2,2,2]*q[1,1,1,1,1] - q[2,1,2,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,1,2,1,2] + q[2,1,1,1,2]*q[1,1,2,2,1]

G2 = graph_from_edges(Directed, [[1,2],[2,3],[4,3],[5,4],[1,5],[1,6],[5,7],[7,6],[2,8],[3,11],[4,12],[6,9],[7,10]])
net2 = phylogenetic_network(G2)
N2 = cavender_farris_neyman_model(net2)
phi2 = parametrization(N2)
H2 = components_of_kernel(2, phi2, show_progress = true)
I2 = ideal(reduce(vcat, collect(values(H2))))

# Ideal generated by
#   -q[2,2,2,2,1]*q[1,2,1,1,2] + q[2,2,2,1,2]*q[1,2,1,2,1] + q[2,2,1,2,2]*q[1,2,2,1,1] - q[2,2,1,1,1]*q[1,2,2,2,2]
#   q[2,2,2,2,1]*q[2,1,1,1,2] - q[2,2,2,1,2]*q[2,1,1,2,1] - q[2,2,1,2,2]*q[2,1,2,1,1] + q[2,2,1,1,1]*q[2,1,2,2,2]
#   q[1,2,2,2,2]*q[1,1,1,1,1] - q[1,2,2,1,1]*q[1,1,1,2,2] - q[1,2,1,2,1]*q[1,1,2,1,2] + q[1,2,1,1,2]*q[1,1,2,2,1]
#   q[2,2,1,2,2]*q[1,1,1,1,1] - q[2,2,1,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,1,2,1]
#   -q[2,2,2,2,1]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]
#   q[2,2,2,2,1]*q[1,1,2,1,2] - q[2,2,2,1,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,2,1,1] + q[2,1,2,1,1]*q[1,2,2,2,2]
#   q[2,1,2,2,2]*q[1,1,1,1,1] - q[2,1,2,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,1,2,1,2] + q[2,1,1,1,2]*q[1,1,2,2,1]
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] + q[2,1,2,2,2]*q[1,2,1,1,2] - q[2,1,1,1,2]*q[1,2,2,2,2]
#   -q[2,2,2,2,1]*q[1,1,1,2,2] + q[2,2,1,2,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,2,2]
#   -q[2,2,2,1,2]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,1,2] - q[2,1,2,1,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,1,1]

#using check_polynomials we can see non-containment of ideals and hence part d of the lemma holds! [this is probs false, calc. again!]