#want to check whether the symmetries of the underlying network topology don't preserve the ideal of the lvl2 network model.

v = [3,1,1]
perms = list_of_perm(v)
rep_list = []
my_list = [[1,3]]

orbit_list = []
    
for h_pair in my_list

    for tau in perms
        if tau(h_pair[1]) > tau(h_pair[2])
            push!(orbit_list, [tau(h_pair[2]), tau(h_pair[1])])
        else
            push!(orbit_list, [tau(h_pair[1]), tau(h_pair[2])])
        end
    end

end

test_list = unique!(orbit_list)

PM1 = draw_network(test_list[1], v)
PM2 = draw_network(test_list[2], v)

phi1 = parametrization(PM1)
H1 = components_of_kernel(2, phi1, show_progress = true)
I1 = ideal(reduce(vcat, collect(values(H1))))

# Ideal generated by
#   q[2,1,2,2,2]*q[1,1,1,1,1] + q[2,1,2,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,1,2,1,2] - q[2,1,1,1,2]*q[1,1,2,2,1]
#   -q[2,2,2,2,1]*q[1,1,1,2,2] + q[2,2,1,2,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,2,2]
#   -q[2,2,2,1,2]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,1,2] - q[2,1,2,1,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,1,1]
#   -q[2,2,2,2,1]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] + q[2,1,2,2,2]*q[1,2,1,1,2] - q[2,1,1,1,2]*q[1,2,2,2,2]

phi2 = parametrization(PM2)
H2 = components_of_kernel(2, phi2, show_progress = true)
I2 = ideal(reduce(vcat, collect(values(H2))))

# Ideal generated by
#   q[2,1,2,2,2]*q[1,1,1,1,1] + q[2,1,2,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,1,2,1,2] - q[2,1,1,1,2]*q[1,1,2,2,1]
#   -q[2,2,2,2,1]*q[1,1,1,2,2] + q[2,2,1,2,2]*q[1,1,2,2,1] - q[2,1,2,2,2]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,2,2]
#   -q[2,2,2,1,2]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,1,2] - q[2,1,2,1,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,1,1]
#   -q[2,2,2,2,1]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] + q[2,1,2,2,2]*q[1,2,1,1,2] - q[2,1,1,1,2]*q[1,2,2,2,2]

g1 = I1.gens
g2 = I2.gens

for i in 1:length(g1)

    println(string(g1[i]) == string(g2[i]))

end

#ideals I1 and I2 are equal in this case, the above loop returns true for each generator, i.e. the generators are all the same.
#note the need for changing above to strings is so that Oscar doesn't complian about the base rings of I1 and I2 being different.

###################
# Another Example #
###################

v = [2,2,0]
perms = list_of_perm(v)
rep_list = []
my_list = [[2,6]]

orbit_list = []
    
for h_pair in my_list

    for tau in perms
        if tau(h_pair[1]) > tau(h_pair[2])
            push!(orbit_list, [tau(h_pair[2]), tau(h_pair[1])])
        else
            push!(orbit_list, [tau(h_pair[1]), tau(h_pair[2])])
        end
    end

end

test_list = unique!(orbit_list)

PM1 = draw_network(test_list[1], v)
PM2 = draw_network(test_list[2], v)

phi1 = parametrization(PM1)
H1 = components_of_kernel(2, phi1, show_progress = true)
I1 = ideal(reduce(vcat, collect(values(H1))))

# Ideal generated by
#   -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] + q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

phi2 = parametrization(PM2)
H2 = components_of_kernel(2, phi2, show_progress = true)
I2 = ideal(reduce(vcat, collect(values(H2))))

# Ideal generated by
#   -q[2,2,2,2]*q[1,1,1,1] + q[2,2,1,1]*q[1,1,2,2] + q[2,1,2,1]*q[1,2,1,2] - q[2,1,1,2]*q[1,2,2,1]

g1 = I1.gens
g2 = I2.gens

for i in 1:length(g1)

    println(string(g1[i]) == string(g2[i]))

end

#Here I1 and I2 are indeed equal.

###################
# Another Example #
###################

#NB v = [4,4,4] is too big for my computer to handle

v = [2,2,1]
perms = list_of_perm(v)
rep_list = []
my_list = [[1,2]]

orbit_list = []
    
for h_pair in my_list

    for tau in perms
        if tau(h_pair[1]) > tau(h_pair[2])
            push!(orbit_list, [tau(h_pair[2]), tau(h_pair[1])])
        else
            push!(orbit_list, [tau(h_pair[1]), tau(h_pair[2])])
        end
    end

end

test_list = unique!(orbit_list)

PM_list = []
phi_list = []
H_list = []
I_list = []

for i in 1:length(test_list)

    PM = draw_network(test_list[i], v)
    phi = parametrization(PM)
    H = components_of_kernel(2, phi, show_progress = true)
    I = ideal(reduce(vcat, collect(values(H))))

    println("done a cycle around the loop.")

    push!(PM_list, PM)
    push!(phi_list, phi)
    push!(H_list, H)
    push!(I_list, I)

end

#Here I_list[1] and I_list[2] are different!

# corresponding to choice [1,2] of reticulation vertices
# julia> I_list[1] 
# Ideal generated by
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] - q[2,1,2,2,2]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,2,2]
#   q[1,2,2,2,2]*q[1,1,1,1,1] + q[1,2,2,1,1]*q[1,1,1,2,2] - q[1,2,1,2,1]*q[1,1,2,1,2] - q[1,2,1,1,2]*q[1,1,2,2,1]
#   q[2,1,2,2,2]*q[1,1,1,1,1] + q[2,1,2,1,1]*q[1,1,1,2,2] - q[2,1,1,2,1]*q[1,1,2,1,2] - q[2,1,1,1,2]*q[1,1,2,2,1]
#   q[2,2,2,2,1]*q[1,1,1,1,1] - q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]

# corresponding to choice [1,5] of reticulation vertices
# julia> I_list[2]
# Ideal generated by
#   q[2,2,2,1,2]*q[1,1,1,2,2] - q[2,2,1,2,2]*q[1,1,2,1,2] - q[2,1,2,2,2]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,2,2]
#   q[2,2,1,2,2]*q[1,1,1,1,1] - q[2,2,1,1,1]*q[1,1,1,2,2] + q[2,1,1,2,1]*q[1,2,1,1,2] - q[2,1,1,1,2]*q[1,2,1,2,1]
#   q[2,2,2,2,1]*q[1,1,1,1,1] - q[2,2,1,1,1]*q[1,1,2,2,1] - q[2,1,2,1,1]*q[1,2,1,2,1] + q[2,1,1,2,1]*q[1,2,2,1,1]
#   -q[2,2,2,1,2]*q[1,1,1,1,1] + q[2,2,1,1,1]*q[1,1,2,1,2] - q[2,1,2,1,1]*q[1,2,1,1,2] + q[2,1,1,1,2]*q[1,2,2,1,1]

#efficient ways to distinguish ideals